### PR TITLE
make first person challenge set players fov to 90

### PR DESCRIPTION
**Pull request by jhh8**

### CODE REVIEW

**Comment by BenLubar** [comment]
We could also change the value in newmapsettings.

**Comment by jhh8** [comment]
you mean fov_desired? how would that work?

**Comment by BenLubar** [comment]
`fov_desired` is clamped to between 20 and 75 in third person and 20 and 120 in first person, so setting `fov_desired` in newmapsettings.cfg to 90 would only change the fov in first person

**Comment by jhh8** [comment]
If we change newmapsettings now it will override it for everyone after the update right? Then i guess we can change fov to 90 internally in transition to asw controls 0

**Comment by Dumbstep** [comment]
Maybe it can be added to the advanced settings

**Comment by BenLubar** [comment]
We could add it to advanced settings (and mark it as FCVAR_ARCHIVE and remove it from newmapsettings), but I'd like to have sliders implemented for advanced settings if we do that.

**Comment by BenLubar** [comment]
> If we change newmapsettings now it will override it for everyone after the update right? Then i guess we can change fov to 90 internally in transition to asw controls 0

the clamped version of fov_desired is recomputed when asw_controls changes, so anything between 75 and 120 will only affect first person

**Comment by jhh8** [comment]
i mean the newmapsettings.cfg will override for everyone and people will lose their configs

**Comment by BenLubar** [comment]
I'd like to get rid of the contents of newmapsettings.cfg eventually - it's weird to have default settings shipped as a config file.

**Comment by BenLubar** [comment]
We could do something with FileProperties in the depot: https://partner.steamgames.com/doc/sdk/uploading#5

I'm not sure if there's any way to prevent the first update that adds that flag from resetting the file, though.

**Comment by Nyubs** [comment]
lul that fake anticheat reacted and admin MANUALLY perma banned me, cause i had in newmapsettings fov desired 120 to watch a cheater.
and it was after the update , which limited it from the default client. so i hope that bad programmer of your anticheat fixed banning for using commands that are not even working anymore.
that would be exacty how you get banned from that admin, using not working FOV in third person. so need make new command or talk to that ADMIN :3

**Pull request closed without merging**
